

from createSchemaDB import exchangePlatform
from createSchemaDB import currency
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

import configuration as config

connection_string="mysql+pymysql://"+config.MYSQL_USER+":"+config.MYSQL_PASS+"@"+config.MYSQL_HOST+":"+config.MYSQL_PORT+"/"+config.MYSQL_DATABASE
engine = create_engine(connection_string)

Session = sessionmaker(engine)

bitcoin=currency("BITCOIN","BTC",1)
ethereum=currency('ETHEREUM','ETH',1)
usDollar=currency('US DOLLAR','USD',1)
aave=currency('AAVE','AAVE',0)
add=currency('ADD','ADD',0)
algorand=currency('Algorand','ALG',0)
ampleforth=currency('Ampleforth','AMP',0)
aragon=currency('Aragon','ANT',0)
airswap=currency('AirSwap','AST',0)
atidium=currency('Atidium','ATD',0)
cosmosAtom=currency('Cosmos-Atom','ATO',0)
avalanche=currency('Avalanche','AVAX',0)
aventus=currency('Aventus','AVT',0)
b21=currency('B21','B21X',0)
balancer=currency('Balancer','BAL',0)
band=currency('Band','BAND',0)
bat=currency('Basic Attention Token','BAT',1)
bitcoinCash=currency('Bitcoin Cash','BCH',0)
bchAbh=currency('BCH ABC','BCHABC',0)
bchNode=currency('BCH Node','BCHN',0)
bnk=currency('BnkToTheFuture','BFT',0)
bfx=currency('BFX Token','BFX',0)
bancor=currency('Bancor','BNT',0)
contentBox=currency('ContentBox','BOX',0)
bitcoinsv=currency('Bitcoin SV','BSV',0)
bitcoinGold=currency('Bitcoin Gold','BTG',0)
btse=currency('BTSE','BTSE',0)
bittorrent=currency('BitTorrent','BTT',0)
swissF=currency('Swiss Franc','CHF',0)
socios=currency('socios.com Chiliz','CHZ',0)
callisto=currency('Callisto','CLO',0)
cindicator=currency('Cindicator','CND',0)
tether=currency('Tether CNHt','CNHT',0)
compund=currency('Compound','COMP',0)
bchabc=currency('BCH ABC Chain Split Token','CSTBCHABC',0)
bchNodeChain=currency('BCH Node Chain Split Token','CSTBCHN',0)
certik=currency('CERTIK','CTK',0)
cortex=currency('Cortex','CTX',0)
daiStable=currency('Dai Stablecoin','DAI',0)
thether=currency('Thether','CNH',0)

bitfinex=exchangePlatform('bitfinex')
cexio=exchangePlatform('cex.io')
kraken=exchangePlatform('kraken')

with Session() as session:
    session.add(bitcoin)
    session.add(ethereum)
    session.add(usDollar)
    session.add(aave)
    session.add(add)
    session.add(algorand)
    session.add(ampleforth)
    session.add(aragon)
    session.add(airswap)
    session.add(atidium)
    session.add(cosmosAtom)
    session.add(avalanche)
    session.add(aventus)
    session.add(b21)
    session.add(balancer)
    session.add(bancor)
    session.add(band)
    session.add(bat)
    session.add(bitcoinCash)
    session.add(bchabc)
    session.add(bchAbh)
    session.add(bchNode)
    session.add(bchNodeChain)
    session.add(bnk)
    session.add(bfx)
    session.add(bancor)
    session.add(contentBox)
    session.add(bitcoinCash)
    session.add(bitcoinGold)
    session.add(bitcoinsv)
    session.add(btse)
    session.add(bittorrent)
    session.add(swissF)
    session.add(socios)
    session.add(callisto)
    session.add(cindicator)
    session.add(tether)
    session.add(compund)
    session.add(certik)
    session.add(cortex)
    session.add(daiStable)
    session.add(thether)


    session.add(bitfinex)
    session.add(cexio)
    session.add(kraken)

    session.commit()
    session.close()
