
from createSchemaDB import exchangePlatform
from createSchemaDB import currency
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker

import configuration as config

connection_string="mysql+pymysql://"+config.MYSQL_USER+":"+config.MYSQL_PASS+"@"+config.MYSQL_HOST+":"+config.MYSQL_PORT+"/"+config.MYSQL_DATABASE
engine = create_engine(connection_string)

Session = sessionmaker(engine)

bitcoin=currency("BITCOIN","BTC")
ethereum=currency('ETHEREUM','ETH')
usDollar=currency('US DOLLAR','USD')
aave=currency('AAVE','AAVE')
add=currency('ADD','ADD')
algorand=currency('Algorand','ALG')
ampleforth=currency('Ampleforth','AMP')
aragon=currency('Aragon','ANT')
airswap=currency('AirSwap','AST')
atidium=currency('Atidium','ATD')
cosmosAtom=currency('Cosmos-Atom','ATO')
avalanche=currency('Avalanche','AVAX')
aventus=currency('Aventus','AVT')
b21=currency('B21','B21X')
balancer=currency('Balancer','BAL')
band=currency('Band','BAND')
bat=currency('Basic Attention Token','BAT')
bitcoinCash=currency('Bitcoin Cash','BCH')
bchAbh=currency('BCH ABC','BCHABC')
bchNode=currency('BCH Node','BCHN')
bnk=currency('BnkToTheFuture','BFT')
bfx=currency('BFX Token','BFX')
bancor=currency('Bancor','BNT')
contentBox=currency('ContentBox','BOX')
bitcoinsv=currency('Bitcoin SV','BSV')
bitcoinGold=currency('Bitcoin Gold','BTG')
btse=currency('BTSE','BTSE')
bittorrent=currency('BitTorrent','BTT')
swissF=currency('Swiss Franc','CHF')
socios=currency('socios.com Chiliz','CHZ')
callisto=currency('Callisto','CLO')
cindicator=currency('Cindicator','CND')
tether=currency('Tether CNHt','CNHT')
compund=currency('Compound','COMP')
bchabc=currency('BCH ABC Chain Split Token','CSTBCHABC')
bchNodeChain=currency('BCH Node Chain Split Token','CSTBCHN')
certik=currency('CERTIK','CTK')
cortex=currency('Cortex','CTX')
daiStable=currency('Dai Stablecoin','DAI')
thether=currency('Thether','CNH')

bitfinex=exchangePlatform('bitfinex')
cexio=exchangePlatform('cex.io')
kraken=exchangePlatform('kraken')

with Session() as session:
    session.add(bitcoin)
    session.add(ethereum)
    session.add(usDollar)
    session.add(aave)
    session.add(add)
    session.add(algorand)
    session.add(ampleforth)
    session.add(aragon)
    session.add(airswap)
    session.add(atidium)
    session.add(cosmosAtom)
    session.add(avalanche)
    session.add(aventus)
    session.add(b21)
    session.add(balancer)
    session.add(bancor)
    session.add(band)
    session.add(bat)
    session.add(bitcoinCash)
    session.add(bchabc)
    session.add(bchAbh)
    session.add(bchNode)
    session.add(bchNodeChain)
    session.add(bnk)
    session.add(bfx)
    session.add(bancor)
    session.add(contentBox)
    session.add(bitcoinCash)
    session.add(bitcoinGold)
    session.add(bitcoinsv)
    session.add(btse)
    session.add(bittorrent)
    session.add(swissF)
    session.add(socios)
    session.add(callisto)
    session.add(cindicator)
    session.add(tether)
    session.add(compund)
    session.add(certik)
    session.add(cortex)
    session.add(daiStable)
    session.add(thether)


    session.add(bitfinex)
    session.add(cexio)
    session.add(kraken)

    session.commit()
